#!/usr/bin/env node
// Downloads the (OFL-licensed) fonts used by the film from Google Fonts and
// writes them to public/fonts, subset to exactly the glyphs the film needs.
// Chinese glyphs are collected from src/copy.js and src/scenes/*.js, so the
// CJK font stays ~100 KB instead of ~10 MB.
//
//   npm run fonts
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'src', 'assets', 'fonts');
fs.mkdirSync(outDir, { recursive: true });

const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

const ASCII = Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)).join('');
const SYMBOLS = '·—–…→←↔∞×≈Σσ√ₖ²³ᵀŁłé“”‘’«»°±−∑∈⊕⊗•▶■□◆✦★♪⁰¹⁴⁵⁶⁷⁸⁹₀₁₂₃';

function collectCJK() {
  const files = [path.join(root, 'src', 'copy.js')];
  const scenesDir = path.join(root, 'src', 'scenes');
  if (fs.existsSync(scenesDir)) {
    for (const f of fs.readdirSync(scenesDir)) if (f.endsWith('.js')) files.push(path.join(scenesDir, f));
  }
  const set = new Set();
  for (const f of files) {
    for (const ch of fs.readFileSync(f, 'utf8')) {
      const c = ch.codePointAt(0);
      if (c > 0x2e7f) set.add(ch); // CJK punctuation, ideographs, full-width forms
    }
  }
  return [...set].sort().join('');
}

const cjk = collectCJK();
const LATIN_TEXT = ASCII + SYMBOLS;

const FONTS = [
  { family: 'Orbitron', axes: 'wght@500;700;900', text: LATIN_TEXT },
  { family: 'Rajdhani', axes: 'wght@500;600;700', text: LATIN_TEXT },
  { family: 'Share Tech Mono', axes: null, text: LATIN_TEXT },
  { family: 'Mr Dafoe', axes: null, text: LATIN_TEXT },
  { family: 'STIX Two Text', axes: 'ital,wght@0,400;0,600;1,400;1,600', text: LATIN_TEXT },
  { family: 'Noto Sans SC', axes: 'wght@300;500;900', text: LATIN_TEXT + cjk },
];

async function get(url, asText) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return asText ? res.text() : Buffer.from(await res.arrayBuffer());
}

const css = [];
for (const font of FONTS) {
  const fam = font.family.replace(/ /g, '+') + (font.axes ? ':' + font.axes : '');
  const url = `https://fonts.googleapis.com/css2?family=${fam}&display=block&text=${encodeURIComponent(font.text)}`;
  const sheet = await get(url, true);
  const faces = sheet.match(/@font-face\s*{[^}]*}/g) || [];
  // Google serves variable fonts as one file per style: keep one copy and
  // declare the weight range instead of duplicating the file per weight.
  const byStyle = new Map();
  for (const face of faces) {
    const style = /font-style:\s*(\w+)/.exec(face)[1];
    const weight = +/font-weight:\s*(\d+)/.exec(face)[1];
    const src = /url\((https:[^)]+)\)/.exec(face)[1];
    const data = await get(src, false);
    const key = style + ':' + data.length + ':' + data.subarray(0, 64).toString('hex');
    if (!byStyle.has(key)) byStyle.set(key, { style, weights: [], data });
    byStyle.get(key).weights.push(weight);
  }
  const slug = font.family.toLowerCase().replace(/ /g, '-');
  for (const { style, weights, data } of byStyle.values()) {
    const variable = weights.length > 1;
    const file = `${slug}${variable ? '' : '-' + weights[0]}${style === 'italic' ? '-italic' : ''}.woff2`;
    const range = variable ? `${Math.min(...weights)} ${Math.max(...weights)}` : `${weights[0]}`;
    fs.writeFileSync(path.join(outDir, file), data);
    css.push(
      `@font-face { font-family: '${font.family}'; font-style: ${style}; font-weight: ${range}; ` +
        `font-display: block; src: url('./assets/fonts/${file}') format('woff2'); }`,
    );
    console.log(`${file.padEnd(34)} ${(data.length / 1024).toFixed(1)} KB  weight ${range}`);
  }
}

fs.writeFileSync(
  path.join(root, 'src', 'fonts.css'),
  '/* Generated by tools/fetch-fonts.mjs — fonts are SIL Open Font License 1.1 (see src/assets/fonts/LICENSE.md). */\n' +
    css.join('\n') +
    '\n',
);
console.log(`\n${css.length} faces, ${cjk.length} CJK glyphs → src/fonts.css`);
